services:
  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_estoque
    restart: always
    environment:
      POSTGRES_USER: igor
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: estoque_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_estoque
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres_db

volumes:
  pgdata: